### acessando via GET
GET http://localhost:3000/subscribers
###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "userName": "Jose Silva",
    "userChannel": "HcodeBrasil"
}
###
GET http://localhost:3000/subscribers/667c25391c2f3849b2b4553b
###
DELETE http://localhost:3000/subscribers/66846b1194730ca0d38558e4
###
PATCH http://localhost:3000/subscribers/667c25391c2f3849b2b4553b
Content-Type: application/json

{
    "userName": "Arianny Cotoca Brilhante"
}